# Generated by Django 4.1.3 on 2022-11-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_categoria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciototal', models.FloatField()),
                ('cantidad', models.PositiveIntegerField()),
                ('notaprestamo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.notaprestamo')),
            ],
        ),
    ]
