# Generated by Django 4.1.3 on 2022-11-29 23:00

from django.db import migrations, models
import libro.models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_notaprestamo_detalleprestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleprestamo',
            name='notaprestamo_id',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.AddField(
            model_name='libro',
            name='file',
            field=models.ImageField(blank=True, upload_to=libro.models.upload_to_pdfs),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to=libro.models.upload_to_images),
        ),
        migrations.DeleteModel(
            name='DetallePrestamo',
        ),
        migrations.DeleteModel(
            name='NotaPrestamo',
        ),
    ]
