# Generated by Django 4.1.3 on 2022-12-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_alter_libro_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Descripciion'),
            preserve_default=False,
        ),
    ]
