# Generated by Django 4.1.3 on 2022-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_libro_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='precio',
        ),
        migrations.AddField(
            model_name='libro',
            name='indice',
            field=models.TextField(default='Indice'),
            preserve_default=False,
        ),
    ]
